"""Admin review schema change

Revision ID: 00667812e389
Revises: 7adc8cc32dbd
Create Date: 2024-03-25 17:23:52.451217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00667812e389"
down_revision: Union[str, None] = "7adc8cc32dbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admin_review", sa.Column("page_type", sa.String()), schema="ssle_metro")
    op.add_column("admin_review", sa.Column("vetted", sa.Boolean()), schema="ssle_metro")
    op.add_column("riders_summary", sa.Column("transport_type", sa.String()), schema="ssle_metro")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("riders_summary", "transport_type", schema="ssle_metro")
    op.drop_column("admin_review", "page_type", schema="ssle_metro")
    op.drop_column("admin_review", "vetted", schema="ssle_metro")
    # ### end Alembic commands ###
